# Generated by Django 5.1.6 on 2025-02-07 03:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='INST001', max_length=50, unique=True, verbose_name='Código')),
                ('numero_serie', models.CharField(blank=True, max_length=100, verbose_name='Número de Série')),
                ('ano_fabricacao', models.IntegerField(blank=True, null=True, verbose_name='Ano de Fabricação')),
                ('data_aquisicao', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Aquisição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço')),
                ('valor_mercado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor de Mercado')),
                ('estado_conservacao', models.CharField(choices=[('novo', 'Novo'), ('excelente', 'Excelente'), ('muito_bom', 'Muito Bom'), ('bom', 'Bom'), ('regular', 'Regular'), ('ruim', 'Ruim')], default='bom', max_length=20, verbose_name='Estado de Conservação')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('vendido', 'Vendido'), ('reservado', 'Reservado'), ('manutencao', 'Em Manutenção')], default='disponivel', max_length=20, verbose_name='Status')),
                ('caracteristicas', models.TextField(blank=True, verbose_name='Características')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Cadastro')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, null=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Instrumento',
                'verbose_name_plural': 'Instrumentos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('pais_origem', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FotoInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='instrumentos/')),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrumentos.instrumento')),
            ],
            options={
                'verbose_name': 'Foto do Instrumento',
                'verbose_name_plural': 'Fotos dos Instrumentos',
                'ordering': ['-data_upload'],
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('marca', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='instrumentos.marca')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'ordering': ['marca__nome', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='instrumento',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrumentos.modelo'),
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='instrumentos.categoria')),
            ],
            options={
                'verbose_name': 'Subcategoria',
                'verbose_name_plural': 'Subcategorias',
                'ordering': ['categoria__nome', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='modelo',
            name='subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='instrumentos.subcategoria'),
        ),
        migrations.AddConstraint(
            model_name='subcategoria',
            constraint=models.UniqueConstraint(fields=('nome', 'categoria'), name='unique_subcategoria_nome_categoria'),
        ),
        migrations.AddConstraint(
            model_name='modelo',
            constraint=models.UniqueConstraint(fields=('nome', 'marca'), name='unique_modelo_nome_marca'),
        ),
    ]
