# Generated by Django 5.1.6 on 2025-02-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='logotipo',
            field=models.ImageField(blank=True, null=True, upload_to='marcas/logos/'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='marca',
            name='pais_origem',
            field=models.CharField(max_length=100),
        ),
    ]
