# Generated by Django 5.1.5 on 2025-01-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos', '0002_alter_fotoinstrumento_descricao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrumento',
            old_name='preco',
            new_name='valor_aquisicao',
        ),
        migrations.AddField(
            model_name='instrumento',
            name='valor_mercado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
