# Generated by Django 5.1.6 on 2025-02-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos', '0002_marca_logotipo_alter_marca_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='pais_origem',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='website',
        ),
        migrations.AddField(
            model_name='marca',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marca',
            name='site',
            field=models.URLField(blank=True, help_text='Site oficial da marca', null=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='logotipo',
            field=models.ImageField(blank=True, help_text='Upload de logotipo da marca. Recomendado: PNG com fundo transparente, mínimo 300x300 pixels.', null=True, upload_to='logos/'),
        ),
    ]
