# Generated by Django 5.1.6 on 2025-02-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos', '0003_remove_marca_pais_origem_remove_marca_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='pais_origem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
