# Generated by Django 5.1.6 on 2025-02-10 02:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos', '0004_marca_pais_origem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotoinstrumento',
            options={'ordering': ['ordem'], 'verbose_name': 'Foto do Instrumento', 'verbose_name_plural': 'Fotos do Instrumento'},
        ),
        migrations.AlterModelOptions(
            name='instrumento',
            options={'ordering': ['-created_at'], 'verbose_name': 'Instrumento', 'verbose_name_plural': 'Instrumentos'},
        ),
        migrations.RemoveField(
            model_name='fotoinstrumento',
            name='data_upload',
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='ano_fabricacao',
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='caracteristicas',
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='estado_conservacao',
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='ultima_atualizacao',
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='valor_mercado',
        ),
        migrations.AddField(
            model_name='fotoinstrumento',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='instrumentos.categoria'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='data_venda',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='estado',
            field=models.CharField(choices=[('novo', 'Novo'), ('usado', 'Usado'), ('restaurado', 'Restaurado')], default='novo', max_length=20),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='instrumentos.marca'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='nome',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='subcategoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='instrumentos.subcategoria'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='valor_venda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fotoinstrumento',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fotoinstrumento',
            name='instrumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='instrumentos.instrumento'),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='data_aquisicao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='modelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='instrumentos.modelo'),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('vendido', 'Vendido'), ('reservado', 'Reservado'), ('manutencao', 'Em Manutenção')], default='disponivel', max_length=20),
        ),
    ]
